
spring:
  datasource:
      url: jdbc:postgresql://hospital_db:5432/hospital_db
      username: user
      password: user
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://keycloak:8080/realms/hospital-realm
          jwk-set-uri: http://keycloak:8080/realms/hospital-realm/protocol/openid-connect/certs
server:
  port: 8181




springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      use-basic-authentication-with-access-code-grant: true
